doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        
        # Importante para MySQL 8.x
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        
        # Mapeo de tipos personalizados para cifrado
        types:
            encrypted_string: App\Shared\Doctrine\Type\EncryptedStringType
        
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Auth:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Entity'
                prefix: 'App\Auth\Entity'
                alias: 'Auth'
            Mensajero:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Mensajero/Entity'
                prefix: 'App\Mensajero\Entity'
                alias: 'Mensajero'
            Envio:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Envio/Entity'
                prefix: 'App\Envio\Entity'
                alias: 'Envio'
            Tracking:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Tracking/Entity'
                prefix: 'App\Tracking\Entity'
                alias: 'Tracking'
            Chat:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Chat/Entity'
                prefix: 'App\Chat\Entity'
                alias: 'Chat'
            Pago:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Pago/Entity'
                prefix: 'App\Pago\Entity'
                alias: 'Pago'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
    
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
