lexik_jwt_authentication:
    secret_key: '%env(JWT_SECRET_KEY)%'
    public_key: '%env(JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    
    access_token_verification:
        signature:
            allowed_algorithms: ['RS256']
            keyset: '%env(JWT_PUBLIC_KEY)%'
    
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: false
            name: BEARER
        query_parameter:
            enabled: false
            name: bearer