mercure:
    # URL del hub Mercure (interna para publicación)
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            # Secret para firmar los JWT de Mercure
            secret: '%env(MERCURE_JWT_SECRET)%'
