[program:messenger_worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/bin/console messenger:consume async doctrine_failure_transport --time-limit=3600 --memory-limit=128M
autostart=true
autorestart=true
numprocs=2
startsecs=5
startretries=3
stopsignal=INT
stopwaitsecs=30
stdout_logfile=/var/www/html/var/logs/worker_%(process_num)02d.log
stderr_logfile=/var/www/html/var/logs/worker_%(process_num)02d_error.log
user=appuser
environment=LC_CTYPE="C.UTF-8"
