<?php

namespace ContainerV0ohjwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2Koikl3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2Koikl3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2Koikl3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'async' => ['privates', 'messenger.transport.async', 'getMessenger_Transport_AsyncService', true],
            'doctrine_failure_transport' => ['privates', 'messenger.transport.doctrine_failure_transport', 'getMessenger_Transport_DoctrineFailureTransportService', true],
            'messenger.transport.async' => ['privates', 'messenger.transport.async', 'getMessenger_Transport_AsyncService', true],
            'messenger.transport.doctrine_failure_transport' => ['privates', 'messenger.transport.doctrine_failure_transport', 'getMessenger_Transport_DoctrineFailureTransportService', true],
        ], [
            'async' => '?',
            'doctrine_failure_transport' => '?',
            'messenger.transport.async' => '?',
            'messenger.transport.doctrine_failure_transport' => '?',
        ]);
    }
}
