<?php

namespace ContainerV0ohjwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_XJFu7m_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.xJFu7m.' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Tracking/MessageHandler/FlushUbicacionesMessageHandler.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['.messenger.handler_descriptor.xJFu7m.'])) {
            return $container->privates['.messenger.handler_descriptor.xJFu7m.'];
        }

        return $container->privates['.messenger.handler_descriptor.xJFu7m.'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Tracking\MessageHandler\FlushUbicacionesMessageHandler(($container->privates['App\\Mensajero\\Repository\\MensajeroRepository'] ?? $container->load('getMensajeroRepositoryService')), $a), []);
    }
}
