<?php

namespace ContainerV0ohjwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_Xo2LlybService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.xo2Llyb' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Envio/MessageHandler/EstadoEnvioChangedMessageHandler.php';

        $a = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['.messenger.handler_descriptor.xo2Llyb'])) {
            return $container->privates['.messenger.handler_descriptor.xo2Llyb'];
        }

        return $container->privates['.messenger.handler_descriptor.xo2Llyb'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Envio\MessageHandler\EstadoEnvioChangedMessageHandler(($container->privates['App\\Envio\\Repository\\EnvioRepository'] ?? $container->load('getEnvioRepositoryService')), $a, ($container->privates['logger'] ?? self::getLoggerService($container))), []);
    }
}
