<?php

namespace ContainerV0ohjwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_TpAG8XPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.TpAG8XP' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Mensajero/Message/ActualizarDisponibilidadMensajerosHandler.php';

        $a = ($container->privates['App\\Mensajero\\Service\\MensajeroService'] ?? $container->load('getMensajeroServiceService'));

        if (isset($container->privates['.messenger.handler_descriptor.TpAG8XP'])) {
            return $container->privates['.messenger.handler_descriptor.TpAG8XP'];
        }

        return $container->privates['.messenger.handler_descriptor.TpAG8XP'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Mensajero\Message\ActualizarDisponibilidadMensajerosHandler($a), []);
    }
}
