<?php

namespace ContainerV0ohjwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_6xLWsz0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.6xLWsz0' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Envio/MessageHandler/NotificarAsignacionMessageHandler.php';

        $a = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['.messenger.handler_descriptor.6xLWsz0'])) {
            return $container->privates['.messenger.handler_descriptor.6xLWsz0'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['.messenger.handler_descriptor.6xLWsz0'])) {
            return $container->privates['.messenger.handler_descriptor.6xLWsz0'];
        }

        return $container->privates['.messenger.handler_descriptor.6xLWsz0'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Envio\MessageHandler\NotificarAsignacionMessageHandler(($container->privates['App\\Envio\\Repository\\EnvioRepository'] ?? $container->load('getEnvioRepositoryService')), ($container->privates['App\\Mensajero\\Repository\\MensajeroRepository'] ?? $container->load('getMensajeroRepositoryService')), $a, $b), []);
    }
}
