<?php

namespace ContainerV0ohjwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualizarDisponibilidadMensajerosCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Mensajero\Command\ActualizarDisponibilidadMensajerosCommand' shared autowired service.
     *
     * @return \App\Mensajero\Command\ActualizarDisponibilidadMensajerosCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Mensajero/Command/ActualizarDisponibilidadMensajerosCommand.php';

        $container->privates['App\\Mensajero\\Command\\ActualizarDisponibilidadMensajerosCommand'] = $instance = new \App\Mensajero\Command\ActualizarDisponibilidadMensajerosCommand(($container->privates['App\\Mensajero\\Service\\MensajeroService'] ?? $container->load('getMensajeroServiceService')));

        $instance->setName('app:mensajeros:actualizar-disponibilidad');
        $instance->setDescription('Actualiza la disponibilidad de todos los mensajeros basado en sus heartbeats recientes');

        return $instance;
    }
}
