<?php

namespace ContainerV0ohjwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualizarDisponibilidadMensajerosCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Mensajero\Command\ActualizarDisponibilidadMensajerosCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Mensajero\\Command\\ActualizarDisponibilidadMensajerosCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:mensajeros:actualizar-disponibilidad', [], 'Actualiza la disponibilidad de todos los mensajeros basado en sus heartbeats recientes', false, #[\Closure(name: 'App\\Mensajero\\Command\\ActualizarDisponibilidadMensajerosCommand')] fn (): \App\Mensajero\Command\ActualizarDisponibilidadMensajerosCommand => ($container->privates['App\\Mensajero\\Command\\ActualizarDisponibilidadMensajerosCommand'] ?? $container->load('getActualizarDisponibilidadMensajerosCommandService')));
    }
}
