<?php

namespace ContainerV0ohjwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMensajeroServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Mensajero\Service\MensajeroService' shared autowired service.
     *
     * @return \App\Mensajero\Service\MensajeroService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Mensajero/Service/MensajeroService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Mensajero\\Service\\MensajeroService'])) {
            return $container->privates['App\\Mensajero\\Service\\MensajeroService'];
        }

        return $container->privates['App\\Mensajero\\Service\\MensajeroService'] = new \App\Mensajero\Service\MensajeroService(($container->privates['App\\Mensajero\\Repository\\MensajeroRepository'] ?? $container->load('getMensajeroRepositoryService')), $a, ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
    }
}
