<?php

namespace ContainerV0ohjwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaker_DoctrineHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'maker.doctrine_helper' shared service.
     *
     * @return \Symfony\Bundle\MakerBundle\Doctrine\DoctrineHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/maker-bundle/src/Doctrine/DoctrineHelper.php';

        $a = ($container->privates['doctrine.orm.default_attribute_metadata_driver'] ?? self::getDoctrine_Orm_DefaultAttributeMetadataDriverService($container));
        $b = ($container->privates['doctrine.orm.default_xml_metadata_driver'] ?? self::getDoctrine_Orm_DefaultXmlMetadataDriverService($container));

        return $container->privates['maker.doctrine_helper'] = new \Symfony\Bundle\MakerBundle\Doctrine\DoctrineHelper('App\\Entity', ($container->services['doctrine'] ?? self::getDoctrineService($container)), ['default' => [['App\\Auth\\Entity', $a], ['App\\Mensajero\\Entity', $a], ['App\\Envio\\Entity', $a], ['App\\Tracking\\Entity', $a], ['App\\Chat\\Entity', $a], ['App\\Pago\\Entity', $a], ['Gesdinet\\JWTRefreshTokenBundle\\Entity', $b], ['Vich\\UploaderBundle\\Entity', $b]]]);
    }
}
