<?php

namespace ContainerV0ohjwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUbicacionMensajeroRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Tracking\Repository\UbicacionMensajeroRepository' shared autowired service.
     *
     * @return \App\Tracking\Repository\UbicacionMensajeroRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryProxy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Tracking/Repository/UbicacionMensajeroRepository.php';

        return $container->privates['App\\Tracking\\Repository\\UbicacionMensajeroRepository'] = new \App\Tracking\Repository\UbicacionMensajeroRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
